import ingraph

print("hash of this is a test")
print(ingraph.hashid("this is a test"))
print("create ingraph_graphs")
print("list of graphs")
print(ingraph.list_graphs())
print(ingraph.create_graph("ingraph_graphs"))
print("delete test graph for fun")
print("list of graphs")
print(ingraph.list_graphs())
print(ingraph.delete_graph("test graph for fun"))
print("list of graphs")
print(ingraph.list_graphs())
print("graph exists test graph for fun")
print(ingraph.graph_exists("test graph for fun"))
print("create test graph for fun")
print(ingraph.create_graph("test graph for fun"))
print("list of graphs")
print(ingraph.list_graphs())
print("graph exists test graph for fun")
print(ingraph.graph_exists("test graph for fun"))
